version: "2"

services:

  frontend:
    image: node:8.11
    ports:
      - "3001:3000"
    volumes:
      - "./frontend/:/app"
    working_dir: /app
    command: /bin/bash -c "yarn install && yarn start"